apiVersion: v1
kind: Service
metadata:
  name: {{ include "avatar-service.fullname" . }}
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "avatar-service.selectorLabels" . | nindent 4 }}
  ports:
  - name: http
    port: {{ .Values.service.httpPort }}
    targetPort: http
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: metrics
