apiVersion: v1
kind: Secret
metadata:
  name: avatar-service-secrets
  labels:
    app: avatar-service
type: Opaque
stringData:
  POSTGRES_DSN: "postgres://gophprofile:changeme@postgres:5432/gophprofile?sslmode=disable"
  S3_ACCESS_KEY: "minioadmin"
  S3_SECRET_KEY: "minioadmin"
  RABBIT_URL: "amqp://guest:guest@rabbitmq:5672/"
