apiVersion: v1
kind: Secret
metadata:
  name: avatar-service-secrets
  labels:
    app: avatar-service
type: Opaque
stringData:
  DB_USER: "gophprofile"
  DB_PASSWORD: "changeme"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"
